# Generated by Django 6.0 on 2025-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='doc_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
